stages:
  - build
job_build:
  script:
    - export ANDROID_HOME=~/Android/android-sdk-linux/
    - cd Source
    - chmod +x gradlew
    - ./gradlew clean build uploadArchives
    - cd android
    - chmod +x gradlew
    - ./gradlew clean utilVersionClass uploadArchives dist
  artifacts:
    name: "shtrihjavapos-${CI_BUILD_REF_NAME}_${CI_PIPELINE_ID}"
    paths:
      - Source/dist/zip/
  stage: build

